/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_misoo_service_Sqr01 */

#ifndef _Included_com_misoo_service_Sqr01
#define _Included_com_misoo_service_Sqr01
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_misoo_service_Sqr01
 * Method:    execute
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_misoo_service_Sqr01_execute
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
